// react/MpReactComponents/src/hooks/useIndexIterator.ts
import { useState } from "react";

export function useIndexIterator( max: number, startIndex: number = 0 ) {
  const [index, goTo] = useState<number>(startIndex);

  function next() {
    goTo((i) => (i + 1) % max );
  }
  
  function previous() {
    goTo((i) => (i - 1 + max) % max);
  }


  return {
    index, next, goTo, previous
  }
}

// qwik/mp-qwik-components/src/hooks/useIndexIterator.ts
import { $, useSignal } from "@builder.io/qwik";

export function useIndexIterator( max: number, startIndex: number = 0 ) {
  const index = useSignal<number>(startIndex);
  
  const goTo = $((target: number) => {
    index.value = target;
  })

  const next = $(() => {
    index.value = (index.value + 1) % max;
  })

  const previous = $(() => {
    index.value = (index.value - 1 + max) % max;
  })

  return {
    index, next, goTo, previous
  }
}
