// qwik/mp-qwik-components/src/components/MpCardCarousel.tsx
import { type Signal, Slot, component$, createContextId, useSignal, useContextProvider, useComputed$ } from "@builder.io/qwik";
import { useIndexIterator } from "../hooks/useIndexIterator";
import { MpCardData } from "../model/MpCardData";

export const MpCardCarouselCtx = createContextId<Readonly<Signal<MpCardData>>>(
  'mp.card-carousel'
);

export interface MpCardCarouselProps {
  items: MpCardData[];
}

function MpCardCarousel$(props: MpCardCarouselProps) {
  const { items } = props;
  
  const containerRef = useSignal<Element>();
  const itemsRef = useSignal<Array<Element | null>>([]) ;

  const { 
    index, 
    next, 
    goTo, 
    previous 
  } = useIndexIterator( items.length, 0 );

  
  const currentCard = useComputed$(() => {
    return items[index.value];
  })

  useContextProvider(MpCardCarouselCtx, currentCard)

  function getScrollWidth() {
    if (containerRef.value) {
      return +itemsRef.value[0]?.clientWidth! + +getComputedStyle(containerRef.value).gap.split('px')[0];
    } else {
      return 0; 
    }
  }

  return <>
    <div class="mp__container">
      <div  class='mp__bg_wrapper' 
            style={{ backgroundImage: `url(${items[index.value].imgUrl})` }} >

        <div class="mp__card">

          <section  class='mp__card__img' 
                    style={{ backgroundImage: `url(${items[index.value].imgUrl})` }}>

            <div class="mp__card__actions">
              <button onClick$={previous}>&lt;</button>
              <button onClick$={next}>&gt;</button>

              <div class="spacer" />

              <span class='index'>
                {(index.value + 1).toString().padStart(2,'0')}
              </span>
            </div>
          </section>

          <section class='mp__card__body'>
            <div class="my-slot">
              <Slot name="card-details"/>
            </div>
            <div class="my-slot-fallback">
              <h1>{currentCard.value.title}</h1>
              <h5>{currentCard.value.description}</h5>
            </div>

            <div class="mp_carousel_container">
              <div  ref={el => containerRef.value = el}
                    class="mp_carousel" 
                    style={{transform: `translateX(-${getScrollWidth() * index.value}px)`}}>
                {
                  ([...items]).slice(1).map( 
                    (x, i) => 
                    <div  key={`carousel_img_${i}}`} 
                          ref={el => (itemsRef.value)[i] = el}>
                      <img 
                        src={x.imgUrl} 
                        onClick$={() => goTo(i+1)}
                      />
                    </div>
                  )
                }
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </>;
}

export default component$(MpCardCarousel$);

// react/MpReactComponents/src/components/MpCardCarousel.tsx
import { useRef } from "react";
import { useIndexIterator } from "../hooks/useIndexIterator";

export interface MpCardData {
  imgUrl: string; 
  title?: string; 
  description?: string;
}

interface IMpCardCarouselProps {
  items: MpCardData[];
  children?: ((item?: MpCardData) => React.ReactNode) | never[]
}

export function MpCardCarousel( props : IMpCardCarouselProps ) {
  const { items, children } = props;

  var templateFn = typeof children === 'function'
    ? children
    : null;

  const containerRef = useRef<HTMLElement | null>();
  const itemsRef = useRef<Array<HTMLElement | null>>([]) ;

  function getScrollWidth() {
    if (containerRef.current) {
      return +itemsRef.current[0]?.clientWidth! + +getComputedStyle(containerRef.current).gap.split('px')[0];
    } else {
      return 0; 
    }
  }

  const { 
    index, 
    next, 
    goTo, 
    previous 
  } = useIndexIterator( items.length, 0 );

  return (
    <>
      <div className="mp__container">
        <div  className='mp__bg_wrapper' 
              style={{ backgroundImage: `url(${items[index].imgUrl})` }} >

          <div className="mp__card">

            <section  className='mp__card__img' 
                      style={{ backgroundImage: `url(${items[index].imgUrl})` }}>

              <div className="mp__card__actions">
                <button onClick={previous}>&lt;</button>
                <button onClick={next}>&gt;</button>

                <div className="spacer" />

                <span className='index'>
                  {(index+1).toString().padStart(2,'0')}
                </span>
              </div>
            </section>

            <section className='mp__card__body'>

              {
                templateFn 
                  ? templateFn(items[index])
                  : 
                  <>
                    <h1>
                      {items[index].title}
                    </h1>

                    <p>
                      {items[index].description}
                    </p>
                  </>
              }

              <div className="mp_carousel_container">
                <div  ref={el => containerRef.current = el}
                      className="mp_carousel" 
                      style={{transform: `translateX(-${getScrollWidth() * index}px)`}}>
                  {
                    ([...items]).slice(1).map( 
                      (x, i) => 
                      <div  key={`carousel_img_${i}}`} 
                            ref={el => (itemsRef.current)[i] = el}>
                        <img 
                          src={x.imgUrl} 
                          onClick={() => goTo(i+1)}
                        />
                      </div>
                    )
                  }
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}

export interface IMpCardContentProps<T> {
  children?: (item: T) => JSX.Element;

  title: string; 
}

export function MpCardContent<T>( _ : IMpCardContentProps<T>) { 
  return null; 
}
